name: Scan Pipeline to build Runner docker images
on:
    push:
        branches:
         - main

permissions:
    contents: read
    packages: write

jobs:
    scanimage:
     name: scan base Image
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: docker login
        uses: docker/login-action@v3 # docker login -u username -p password
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Pull image
        run: |
          docker pull python:3.12-slim
          docker pull vitamojo/mysql5:latest
          docker images
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vitamojo/mysql5:latest'
          scan-type: image
          format: 'cyclonedx'
          output: 'trivy-results.cdx'
          severity: "MEDIUM,HIGH,CRITICAL"
          scanners: "vuln,secret,misconfig,license"
      - name: Upload Docker Image Scan results
        uses: actions/upload-artifact@v5.0.0
        with:
           name: scanresults
           path: trivy-results.cdx
      - uses: dataswift/gha-trivy@v3.0.0
        with:
          token: ${{ secrets.GITHUBTOKEN }}
          image: vitamojo/mysql5:latest